### ISSUE TITLE
Incorrect type used for middleware `next` function

### ISSUE THREAD

**Issue by anthonyec** [bbc/http-transport#39]
## Problem
Currently the type for the `next` function in middleware has this type:
https://github.com/bbc/http-transport/blob/627d4507c49d13ade2fda8fef708fef4bfbdda6b/index.d.ts#L14

This says it can return a function that returns void (`() => void`) or returns a promise that resolves void (`Promise<void>`). However the promise bit is incorrect. The `next` argument is **always a function** but one that returns a promise. It isn't a promise in itself.

In most use cases I've seen ([1](https://github.com/bbc/http-transport-xray/blob/6fde43842fd4d835bdc36df6d8f1ac7d594b6279/lib/xray.js#L15), [2](https://github.com/bbc/http-transport-rate-limiter/blob/776c59f10a50856f75710f2e3146ddb2fb90d0e8/lib/rateLimiter.js#L14), [3](https://github.com/bbc/http-transport-cache/blob/ea3074d72b001db2e594fb246f2c7a26cfee2d53/lib/staleIfError.js#L39), [4](https://github.com/bbc/http-transport-statsd/blob/5dfb3c59b128cdba99acec6789269e7aa340ff57/lib/stats.js#L14)), it's used like:
```js
await next();
```

However, the current type suggestions it should be used like:
```js
await next;
```

Kind of hard to explain but yeah.

## Solution

I think the solution is to change the type to this:

```ts
next: () => void | () => Promise<void>
```

Possibly even this(?):
```ts
next: () => Promise<void>
```

**Comment by vaughandroid** [comment]
I don't think this is actually an issue.

The bug is suggesting the type should be read like this:

```ts
next: (() => void) | Promise<void>
```

whereas actually it should be read like this:

```ts
next: () => (void | Promise<void>)
```

I interpreted it the same way as the bug at first too! To try and avoid confusion in future, I've updated the code to match the second example.
